### Test Koneksi
GET http://localhost:3000/api

### Token
GET http://localhost:3000/api/siswa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInJvbGUiOiJHVVJVIiwiaWF0IjoxNzU1MTM3NTc3LCJleHAiOjE3NTUyMjM5Nzd9.7xuZAwxDo-MIlv4-cOd-r3T7vrfNSRo2MxXLDseQU9c

### Login sebagai Guru
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### Informasi pengguna

GET http://localhost:3000/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NTI2NjQ2OSwiZXhwIjoxNzU1MzUyODY5fQ.NIh4w6t9If0vIOJzMYPqY0kManjrhIT0-GyjK5PamaU